import type MarkdownIt from "markdown-it";
import type StateBlock from "markdown-it/lib/rules_block/state_block.mjs";
import { t } from "../../core/i18nCore";

/**
 * The mkdocstrings auto-documentation block: `::: identifier` plus — optionally —
 * indented YAML options underneath it:
 *
 *     ::: fastapi.status
 *         options:
 *           show_root_heading: true
 *
 * The content of such a block (signatures, docstring, attributes) is assembled by
 * the Python mkdocstrings plugin while the site is built — it cannot be reproduced
 * without Python. So we draw a placeholder card and keep the source itself in
 * `data-mkdocstrings-src`: the block becomes an “island” of the visual editor (edited
 * as text as a whole), and its YAML indentation does not drift when neighbours are
 * edited. Without this rule `:::` would be an ordinary paragraph — editing would
 * collapse the options onto one line and break the configuration.
 */
export function mkdocstringsPlugin(md: MarkdownIt): void {
  md.block.ruler.before("paragraph", "mkdocstrings", mkdocstringsBlock, {
    alt: ["paragraph", "reference", "blockquote"],
  });

  md.renderer.rules.mkdocstrings = (tokens, idx) => {
    const token = tokens[idx];
    const src = token.content;
    const identifier = String(token.meta?.identifier ?? "");
    const options = src
      .split("\n")
      .slice(1)
      .filter((l) => l.trim() !== "");
    const srcLine = token.attrGet("data-src-line");
    const srcAttrs = srcLine
      ? ` data-src-line="${srcLine}" data-src-end="${token.attrGet("data-src-end") ?? srcLine}"`
      : "";
    const optionsHtml =
      options.length > 0
        ? `<pre class="mkdocstrings-options">${escapeHtml(dedent(options).join("\n"))}</pre>`
        : "";
    return (
      `<div class="mkdocstrings" data-block-type="mkdocstrings"${srcAttrs}` +
      ` data-mkdocstrings-src="${escapeAttr(src)}">` +
      `<div class="mkdocstrings-head">` +
      `<span class="mkdocstrings-badge">API</span>` +
      `<code class="mkdocstrings-id">${escapeHtml(identifier)}</code>` +
      `</div>` +
      optionsHtml +
      `<p class="mkdocstrings-note">${escapeHtml(t("The reference is generated by the mkdocstrings plugin when the site is built."))}</p>` +
      `</div>\n`
    );
  };
}

function mkdocstringsBlock(
  state: StateBlock,
  startLine: number,
  endLine: number,
  silent: boolean,
): boolean {
  // An indent of 4+ spaces is a code block, not a marker (the CommonMark rule).
  if (state.sCount[startLine] - state.blkIndent > 3) {
    return false;
  }
  const start = state.bMarks[startLine] + state.tShift[startLine];
  const first = state.src.slice(start, state.eMarks[startLine]);
  const marker = /^:::\s+(\S+)\s*$/.exec(first);
  if (!marker) {
    return false;
  }
  if (silent) {
    return true;
  }

  // The options are the consecutive non-blank lines indented deeper than the marker.
  // A blank line is not taken in: the next block of the document already starts
  // after it, and capturing it would mean “swallowing” foreign text into the island.
  const baseIndent = state.sCount[startLine];
  let nextLine = startLine + 1;
  while (nextLine < endLine && !state.isEmpty(nextLine) && state.sCount[nextLine] > baseIndent) {
    nextLine++;
  }

  const token = state.push("mkdocstrings", "div", 0);
  token.block = true;
  // The container's indent (admonition/tab) is stripped — serialization of the
  // nested block puts it back; the relative YAML indentation stays as in the file.
  token.content = state.getLines(startLine, nextLine, state.blkIndent, false).replace(/\n$/, "");
  token.map = [startLine, nextLine];
  token.meta = { blockType: "mkdocstrings", identifier: marker[1] };
  state.line = nextLine;
  return true;
}

/** Strips the common indent of the option lines — the card shows them on their own. */
function dedent(lines: string[]): string[] {
  const indent = Math.min(...lines.map((l) => l.length - l.trimStart().length));
  return lines.map((l) => l.slice(indent));
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] as string);
}

function escapeAttr(s: string): string {
  return s.replace(
    /[&<>"\n]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "\n": "&#10;" })[c] as string,
  );
}
